# Generated by Django 4.2.5 on 2023-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='link',
            new_name='profile_picture',
        ),
    ]
