# Generated by Django 4.2.5 on 2023-10-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_trial_ended_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_time',
            field=models.DateTimeField(),
        ),
    ]
